#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	path_to_file=$1
	username=$2
	server_ip=$3
	private_key=$4

	ssh -o StrictHostKeyChecking=no -i "$private_key" "$path_to_file" "$username@$server_ip":~/
fi
