#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

	# Assigns parameter to variable

	file_path=$1
	ip=$2
	username=$3
	key_path=$4

	# Disabling strict host key checking

	ssh -o "StrictHostKeyChecking no" -i "$key_path" "$file_path" "$username@$ip:~/"

	# Checks if transfer was successful

	if [ $? -eq 0 ]
	then
		echo "FILE_WAS_SUCCESSFULLY_TRANSFERRED"
	else
		echo "FAILED_TO_TRANSFER_FILE"
	fi
