#!/usr/bin/env bash
# Bash script to configure Nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page.

# Install Nginx and allow it to listen on port 80
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw 'Nginx HTTP'

# Write Hello World! into a file named index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure it to listen at port 80
echo "server {
	listen 80;
	listen[::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.htm;
}" > /etc/nginx/sites-available/default

# Check if the previous command disrupted Nginx configuration
sudo nginx -t

# Edits the configuration file of nginx
tag="\\\n\tlocation \/redirect_me {\n\t\treturn 301 http:\/\/www.google.com;\n\t}"
sed -i "7i $tag" /etc/nginx/sites-available/default

# Creates and configures custom 404 file to render "Ceci n'est pas une page"
touch /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
var="\\\n\terror_page 404 /404.html;\n\tlocation /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sed -i "11i $var" /etc/nginx/sites-available/default

# Reload Nginx
sudo service nginx restart
