#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
